const styles = {
  visualizationBlock: {
    width: "80%", // mobile-first
    maxWidth: "700px",
    minHeight: "250px",
    background: "linear-gradient(135deg, #181a1b 70%, #232946 100%)",
    borderRadius: "1.4rem",
    border: "4px solid #232946",
    display: "flex",
    flexDirection: "column",
    padding: "1.5rem",
    margin: "auto",
    boxShadow: "0 8px 32px #23294688",
    overflow: "hidden",
    color: "#FDE047",
    fontWeight: 600,
    fontSize: "1rem",
    justifyContent: "center",
    alignItems: "center",
  },
  row: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginBottom: "1.5rem",
  },
  visualizationRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "1rem",
    flexWrap: "wrap",
  },
  explanationRow: {
    width: "90%",
    background: "#232946",
    borderRadius: "0.75rem",
    padding: "0.8rem",
    marginBottom: "1rem",
    color: "#FFD600",
    fontSize: "0.95rem",
    lineHeight: "1.3rem",
  },
  codeRow: {
    width: "100%",
    background: "#181a1b",
    borderRadius: "0.75rem",
    padding: "1rem",
    color: "#FFD600",
    fontSize: "0.9rem",
    overflowX: "auto",
  },
  elevator: {
    width: "50px",
    height: "100px",
    background: "linear-gradient(135deg, #A569BD 60%, #00BFFF 100%)",
    borderRadius: "0.75rem",
    margin: "0 1rem",
    display: "inline-block",
    boxShadow: "0 2px 12px #A569BD55",
    border: "2px solid #232946",
    color: "#F0F0F0",
    fontWeight: 700,
    fontSize: "1rem",
    textAlign: "center",
    lineHeight: "100px",
  },
  floor: {
    background: "#FFD600",
    borderRadius: "0.5rem",
    margin: "0 0.5rem",
    padding: "4px 10px",
    display: "inline-block",
    boxShadow: "0 2px 12px #FFD60055",
    border: "2px solid #232946",
    color: "#232946",
    fontWeight: 700,
    fontSize: "0.95rem",
    textAlign: "center",
    lineHeight: "28px",
  },
  flow: {
    display: "inline-block",
    color: "#fff",
    fontWeight: 700,
    fontSize: "0.95rem",
    textAlign: "center",
    lineHeight: "28px",
  },
  car: {
    color: "transparent",
    width: "20px",
    height: "20px",
    background: "#FFD600",
    borderRadius: "0.25rem",
    margin: "0 6px",
  },
  arrow: {
    fontSize: "1rem",
    color: "#FFD600",
    margin: "0 4px",
  },
  lane: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "12px",
  },
  pin: {
    width: "10px",
    height: "10px",
    background: "#FFD600",
    borderRadius: "50%",
    margin: "0 2px",
  },

  // Media Queries (responsive)
  "@media (min-width: 600px)": {
    visualizationBlock: {
      fontSize: "1.1rem",
      minHeight: "280px",
      padding: "1.8rem",
    },
    elevator: {
      width: "55px",
      height: "110px",
      fontSize: "1.05rem",
      lineHeight: "110px",
    },
    floor: {
      fontSize: "1rem",
      padding: "5px 12px",
    },
    flow: {
      fontSize: "1rem",
    },
  },
  "@media (min-width: 900px)": {
    visualizationBlock: {
      fontSize: "1.2rem",
      minHeight: "300px",
      padding: "2rem",
    },
    elevator: {
      width: "60px",
      height: "120px",
      fontSize: "1.1rem",
      lineHeight: "120px",
    },
    floor: {
      fontSize: "1rem",
      padding: "6px 12px",
    },
    flow: {
      fontSize: "1rem",
    },
  },
};

export default styles;
