const styles = {
  visualizationBlock: {
    width: "100%",
    maxWidth: "700px",
    minHeight: "300px",
    background: "linear-gradient(135deg, #181a1b 70%, #232946 100%)",
    borderRadius: "22px",
    border: "4px solid #232946",
    display: "flex",
    flexDirection: "column",
    padding: "2rem",
    margin: "auto",
    boxShadow: "0 8px 32px #23294688",
    overflow: "hidden",
    color: "#FDE047",
    fontWeight: 600,
    fontSize: "1.2rem",
    justifyContent: "center",
    alignItems: "center",
  },
  row: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginBottom: "2rem",
  },
  visualizationRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "1rem",
    flexWrap: "wrap",
  },
  explanationRow: {
    width: "90%",
    background: "#232946",
    borderRadius: 12,
    padding: "1rem",
    marginBottom: "1rem",
    color: "#FFD600",
    fontSize: "1rem",
    lineHeight: "1.4rem",
  },
  codeRow: {
    width: "100%",
    background: "#181a1b",
    borderRadius: 12,
    padding: "1.2rem",
    color: "#FFD600",
    fontSize: "0.95rem",
    overflowX: "auto",
  },
  elevator: {
    width: 60,
    height: 120,
    background: "linear-gradient(135deg, #A569BD 60%, #00BFFF 100%)",
    borderRadius: 12,
    margin: "0 18px",
    display: "inline-block",
    boxShadow: "0 2px 12px #A569BD55",
    border: "2px solid #232946",
    color: "#F0F0F0",
    fontWeight: 700,
    fontSize: "1.1rem",
    textAlign: "center",
    lineHeight: "120px",
  },
  floor: {
    background: "linear-gradient(90deg, rgb(165, 105, 189), rgb(93, 173, 226))",
    borderRadius: 8,
    margin: "0 8px",
    padding: "6px 12px",
    display: "inline-block",
    boxShadow: "0 2px 12px #FFD60055",
    border: "2px solid #232946",
    color: "#232946",
    fontWeight: 700,
    fontSize: "1rem",
    textAlign: "center",
    lineHeight: "30px",
  },
  flow: {
    display: "inline-block",
    color: "#fff",
    fontWeight: 700,
    fontSize: "1rem",
    textAlign: "center",
    lineHeight: "30px",
  },
};

export default styles;